/* maranderson, equipCycle.js */
var index = 0;

function goRight(){
	index = index + 1;
	if(index == 5){
		index= 0;
	}
	main();
}

function goLeft(){
	index = index - 1;
	if(index == -1){
		index= 4;
	}
	main();
}

function main(){
	var equip = document.getElementsByClassName("Equipment")[0];
	var img = document.getElementById("equipPicture");
	if(index == 0){
		equip.getElementsByClassName("select")[0].innerHTML = "<strong>Togs:</strong><br/><br/> \u2219 Goes with out saying, (I hope). Togs will be required, speedos for chaps, one-piece swimsuit for women. Don't try with shorts and/or t-shirt; the drag generated by baggy clothing is prohibitive. </br></br> <strong>Hat:</strong><br/><br/> \u2219 A water-polo style hat with ear protectors."
		img.src = "../Images/images-2.jpg";
	}if(index == 1){
		equip.getElementsByClassName("select")[0].innerHTML = "<strong>Mask:</strong><br/><br/> \u2219 Well fitting, low-volume. Make sure you have reasonable peripheral vision otherwise other players can creep up un-noticed. Make sure that there is a pillar between the two eye pieces. The glass must be safety glass. </br></br> <strong>Snorkel:</strong><br/><br/> \u2219 The biggest bore snorkel you can get. Dont get one with fancy valves or other gizmos, just one that allows you to get air in at the maximum possible rate. You'll thank me for this later."
		img.src = "../Images/images.jpg";
	}if(index == 2){
		equip.getElementsByClassName("select")[0].innerHTML = "<strong>Glove:</strong><br/><br/> \u2219 A glove is worn on the hand holding your stick. It has two purposes:<br/><br/> 1.To protect your knuckles from the bottom of the pool. Some of the tiles have small chips on them and they are very sharp to the unprotected knuckle.<br/><br/>		2.To protect your fingers (and indeed entire hand) when they are (inevitably) hit by either the puck or another players stick. <br/><br/> \u2219 To get your own glove you can either: <br/><br/>		1. Make one. It's easy all you need is a gardening glove and a tube of silicone bathroom sealant. I am sure you can work it out from there. <br/><br/>		2. Buy one. Saves a lot of time and mess. You can buy them online for about $50"
		img.src = "../Images/images-1.jpg";
	}if(index == 3){
		equip.getElementsByClassName("select")[0].innerHTML = "<strong>Stick:</strong><br/><br/> \u2219 In the old days people use to carve their own sticks out of bits of hard wood. Nowadays sticks are made of composite plastic and are available in a multitude of sizes and styles."
		img.src = "../Images/sticks.jpg";
	}if(index == 4){
		equip.getElementsByClassName("select")[0].innerHTML = "<strong>Fins:</strong><br/><br/> \u2219 There are many styles of fins that vary wildly in price. The expensive fins are not always the best fins... for you. If at all possible try a variety of fins (ask people at the club they will let you try their fins) until you find a style that works for the way you swim. <br/><br/> \u2219 The things you wear on your feet are called fins, not flippers. 'Flipper' was a dolphin."
		img.src = "../Images/images-4.jpg";
	}
}

function setup(){
	var leftArrow = document.getElementById("leftArrow");
	var rightArrow = document.getElementById("rightArrow");
	leftArrow.onclick = goLeft;
	rightArrow.onclick = goRight;
}

if(document.getElementById){
	window.onload = setup;
}
